[package]
name = "zk-age-verification"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-ff = "0.5.0"
ark-relations = "0.5.0"
ark-serialize = "0.5.0"
ark-std = "0.5.0"

ark-test-curves = { version = "0.5.0", features = ["bls12_381_scalar_field", "bls12_381_curve"] }

